---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install Helm diff plugin
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff

    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Deploy mysql chart
      kubernetes.core.helm:
        name: mysqld
        chart_ref: bitnami/mysql
        chart_version: 8.8.1
        create_namespace: true
        release_namespace: mysqld
        values:
          auth:
            rootPassword: dGVzdDEyMw==
            password: dGVzdDEyMw==
            forcePassword: true

    - name: Check RC status of command executed
      kubernetes.core.k8s_exec:
        namespace: mysqld
        pod: mysql-0
        command: ls -altr
        validate_certs: False
      register: command_status
      ignore_errors: True
